insert:
  cover.jpg:
    image_type: cover
  insert1.jpg:
    image_type: single
  insert2.jpg:
    image_type: double
  insert3.jpg:
    image_type: double
  insert4.jpg:
    image_type: double
  insert5.jpg:
    image_type: single
  titlepage.jpg:
    image_type: titlepage
  toc.jpg:
    image_type: toc

chapter:
  1.jpg:
    image_type: double
  2.jpg:
    image_type: double
  3.jpg:
    image_type: double
  4.jpg:
    image_type: double
  5.jpg:
    image_type: double
