insert:
  coverins.jpg:
    image_type: single
  ins1.jpg:
    image_type: double
  ins2.jpg:
    image_type: double
  toc.jpg:
    image_type: double

chapter:
  1.jpg:
    image_type: double
  2.jpg:
    image_type: double
  3.jpg:
    image_type: double
  4.jpg:
    image_type: double
  5.jpg:
    image_type: double